name: test-ci

on:
  push:
    branches: [ foo ]

jobs:
  wfcvm-test-mac:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: set UCVM_SRC_PATH 
      run: echo "UCVM_SRC_PATH=$RUNNER_WORKSPACE/wfcvm/ucvm" >> $GITHUB_ENV
    - name: set UCVM_INSTALL_PATH 
      run: echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/wfcvm/target" >> $GITHUB_ENV
#    - name: Start SSH via Ngrok
#      if: ${{ success() }}
#      uses: luchihoratiu/debug-via-ssh@main
#      with:
#            NGROK_AUTH_TOKEN: ${{ secrets.NGROK_TOKEN }}
#            NGROK_TIMEOUT: 3000
#            SSH_PASS: ${{ secrets.NGROK_SECRET }}
### build ucvm(main) first 
    - id: get-ucvm 
      uses: actions/checkout@v2
      with: 
        repository: 'SCECcode/UCVM'
        ref: main 
        path: ucvm
    - id: look-around
      run: ( echo " wfcvm-ucvm-ci:pwd =>";pwd;
             echo " wfcvm-ucvm-ci:UCVM_SRC_PATH =>"$UCVM_SRC_PATH;
             echo " wfcvm-ucvm-ci:UCVM_INSTALL_PATH =>"$UCVM_INSTALL_PATH;
             echo " wfcvm-ucvm-ci:RUNNER_WORKSPACE =>"$RUNNER_WORKSPACE;
             echo " wfcvm-ucvm-ci:github.action_path =>"${{ github.action_path }};)
      shell: bash
    - id: build-ucvm
      uses: SCECcode/UCVM/.github/actions/build-action@v1
      with:
         initiating-repo: 'wfcvm'
         target-model: 'wfcvm'
    - name: Start SSH via Ngrok when ucvm-test.sh fails
      if: ${{ failure() }}
      uses: luchihoratiu/debug-via-ssh@main
      with:
            NGROK_AUTH_TOKEN: ${{ secrets.NGROK_TOKEN }}
            NGROK_TIMEOUT: 6000
            SSH_PASS: ${{ secrets.NGROK_SECRET }}
